### ISSUE TITLE
OP-BackChannel-RpInitLogout-all

### ISSUE THREAD

**Issue by panva** [openid-certification/oidctest#154]
Status: 🔴 

```
********************************************************************************

Something went wrong! If you know or suspect you know why, then try to
fix it. If you have no idea, then please tell us at certification@oidf.org
and we will help you figure it out.

********************************************************************************


Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/oidctest-0.8.1-py3.6.egg/oidctest/optt/__init__.py", line 316, in _endpoint
    resp = self.tester.handle_request(request, **kwargs)
TypeError: handle_request() got an unexpected keyword argument 'state'
```

~1) the above error is returned every time now~
2) in my previous testing if the tool received two backchannel logout triggers it failed as well, mind you it will be common for the tool to receive more logout notifications because of dynamic client sessions that will be registered on the OP. Suggestion: make the backchannel logout uri unique for the client that's just registered for this test run, ignore the rest.

**Comment by rohe** [comment]
If Hans updates new_op with the latest code this should be fixed now.

**Comment by panva** [comment]
Including point #2?

**Comment by rohe** [comment]
No, that I'm working on.

**Comment by zandbelt** [comment]
deployed now

**Comment by panva** [comment]
no change, still 🔴

**Comment by rohe** [comment]
Time to deploy a new version

> 5 apr. 2019 kl. 14:18 skrev Hans Zandbelt <notifications@github.com>:
> 
> deployed now
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

—Roland
The reward for conformity was that everyone liked you except yourself. -Rita Mae Brown, writer (b. 28 Nov 1944)

**Comment by zandbelt** [comment]
done

**Comment by panva** [comment]
Updated the description, a simple case where the tool only receives the single backchannel notification is now working. In case it gets multiple (point 2) - still fails with this

```
********************************************************************************

Something went wrong! If you know or suspect you know why, then try to
fix it. If you have no idea, then please tell us at certification@oidf.org
and we will help you figure it out.

********************************************************************************


Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/oidctest-0.8.1-py3.6.egg/oidctest/optt/__init__.py", line 316, in _endpoint
    resp = self.tester.handle_request(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/otest-0.7.4-py3.6.egg/otest/aus/tool.py", line 237, in handle_request
    item = self.sh["sequence"][index]
IndexError: list index out of range
```

**Comment by rohe** [comment]
I'm working on (2). 
Unfortunately the web framework I use is not very helpful.

**Comment by rohe** [comment]
Check in code that hopefully will fix this.

**Comment by zandbelt** [comment]
deployed now
